### ISSUE TITLE
ChannelBot just flatout ignored my commands.

### ISSUE THREAD

**Issue by FMFields** [PintTheDragon/ChannelMessage#3]

**Comment by PintTheDragon** [comment]
Everything is working fine on my end. Make sure that it has permissions to speak in and read the current channel you're in, and try mentioning it instead of using a prefix (``@ChannelMessage help`` instead of ``.help``). Let me know how that goes!

**Comment by PintTheDragon** [comment]
I haven't gotten any response and I can't reproduce this issue so I'm closing this now.
